import { useEffect, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  MenuItem,
  FormControlLabel,
  Switch,
  Stack,
} from '@mui/material';
import { coerceValue } from '../../utils/agGridHelpers';

/**
 * Is a column filled in by the database itself (so the form should omit it)?
 *
 * For a live Postgres schema we have explicit flags. For the mock schema (no
 * flags), fall back to "the primary key is auto-generated".
 */
function isAutoGenerated(col, primaryKey) {
  if (
    col.is_identity !== undefined ||
    col.has_default !== undefined ||
    col.is_generated !== undefined
  ) {
    return Boolean(col.is_identity || col.has_default || col.is_generated);
  }
  return col.column_name === primaryKey;
}

/**
 * RecordFormDialog
 * ----------------
 * A dialog whose fields are generated dynamically from schema metadata, used to
 * add a new row.
 *
 * Columns the database fills itself (identity, serial/defaults, generated) are
 * omitted; everything the user must or may provide is shown — including the
 * primary key when it has no default. NOT NULL columns are marked required and
 * validated. Enum columns render as a dropdown of their allowed values.
 */
export default function RecordFormDialog({
  open,
  schema,
  tableName,
  primaryKey,
  onClose,
  onSubmit,
}) {
  // Columns the user actually fills in.
  const editableCols = (schema || []).filter(
    (c) => !isAutoGenerated(c, primaryKey)
  );

  const [values, setValues] = useState({});
  const [errors, setErrors] = useState({});
  const [submitting, setSubmitting] = useState(false);

  // Reset the form whenever the dialog opens for a (possibly different) table.
  useEffect(() => {
    if (!open) return;
    const initial = {};
    editableCols.forEach((c) => {
      initial[c.column_name] =
        c.data_type.toLowerCase() === 'boolean' ? false : '';
    });
    setValues(initial);
    setErrors({});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, tableName]);

  const setField = (name, value) =>
    setValues((prev) => ({ ...prev, [name]: value }));

  const validate = () => {
    const next = {};
    editableCols.forEach((c) => {
      const v = values[c.column_name];
      const empty = v === '' || v === undefined || v === null;
      // Required = NOT NULL with no default (boolean always has a value).
      if (c.required && empty && c.data_type.toLowerCase() !== 'boolean') {
        next[c.column_name] = 'Required';
      }
    });
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;
    setSubmitting(true);
    // Coerce every field to its column's JS type; drop empty optional values so
    // the DB can apply its own defaults / nulls.
    const record = {};
    editableCols.forEach((c) => {
      const coerced = coerceValue(c.data_type, values[c.column_name]);
      if (coerced !== null || c.required) record[c.column_name] = coerced;
    });
    try {
      await onSubmit(record);
    } finally {
      setSubmitting(false);
    }
  };

  const renderField = (col) => {
    const t = col.data_type.toLowerCase();
    const name = col.column_name;
    const label = col.required ? `${name} *` : name;
    const enumValues = Array.isArray(col.enum_values) ? col.enum_values : null;
    const helper = errors[name] || col.data_type;
    const error = Boolean(errors[name]);

    if (t === 'boolean') {
      return (
        <FormControlLabel
          key={name}
          control={
            <Switch
              checked={Boolean(values[name])}
              onChange={(e) => setField(name, e.target.checked)}
            />
          }
          label={name}
        />
      );
    }

    if (enumValues) {
      return (
        <TextField
          key={name}
          select
          label={label}
          value={values[name] ?? ''}
          onChange={(e) => setField(name, e.target.value)}
          fullWidth
          size="small"
          error={error}
          helperText={helper}
        >
          {!col.required && (
            <MenuItem value="">
              <em>—</em>
            </MenuItem>
          )}
          {enumValues.map((opt) => (
            <MenuItem key={opt} value={opt}>
              {opt}
            </MenuItem>
          ))}
        </TextField>
      );
    }

    let type = 'text';
    let extraProps = {};
    if (t === 'integer' || t === 'bigint' || t === 'smallint') {
      type = 'number';
      extraProps = { inputProps: { step: 1 } };
    } else if (t === 'numeric' || t === 'decimal' || t.includes('double') || t === 'real') {
      type = 'number';
      extraProps = { inputProps: { step: 'any' } };
    } else if (t === 'date') {
      type = 'date';
      extraProps = { InputLabelProps: { shrink: true } };
    } else if (t.includes('timestamp') || t.includes('time')) {
      type = 'datetime-local';
      extraProps = { InputLabelProps: { shrink: true } };
    }

    return (
      <TextField
        key={name}
        label={label}
        type={type}
        value={values[name] ?? ''}
        onChange={(e) => setField(name, e.target.value)}
        fullWidth
        size="small"
        error={error}
        helperText={helper}
        {...extraProps}
      />
    );
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <form onSubmit={handleSubmit}>
        <DialogTitle sx={{ textTransform: 'capitalize' }}>
          Add row to {tableName}
        </DialogTitle>
        <DialogContent dividers>
          <Stack spacing={2} sx={{ pt: 1 }}>
            {editableCols.map(renderField)}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={onClose} disabled={submitting}>
            Cancel
          </Button>
          <Button type="submit" variant="contained" disabled={submitting}>
            {submitting ? 'Adding…' : 'Add Row'}
          </Button>
        </DialogActions>
      </form>
    </Dialog>
  );
}
